# To do later: Add examples for each code smell

CODE_SMELLS = [
    {
        "id": "long_method",
        "name": "Long Method",
        "description": "A method is too long (usually above 10-20 lines) and violates the single responsibility principle",
        "treatments": [
            "Extract Method",
            "Replace Temp with Query, Introduce Parameter Object or Preserve Whole Object",
            "Decompose Conditional",
        ],
    },
    {
        "id": "large_class",
        "name": "Large Class",
        "description": "A class is too long and violates the single responsibility principle",
        "treatments": [
            "Extract Class",
            "Extract Subclass",
            "Extract Interface",
            "Duplicate Observed Data",
        ],
    },
    {
        "id": "primitive_obsession",
        "name": "Primitive Obsession",
        "description": "Use of primitives instead of small objects for simple tasks (such as currency, ranges, special strings for phone numbers, etc.)",
        "treatments": [
            "Replace Data Value with Object",
            "Introduce Parameter Object or Preserve Whole Object",
            "Replace Type Code with Class, Replace Type Code with Subclasses or Replace Type Code with State/Strategy",
            "Replace Array with Object",
        ],
    },
    {
        "id": "long_parameter_list",
        "name": "Long Parameter List",
        "description": "More than three or four parameters for a method",
        "treatments": [
            "Replace Parameter with Method Call",
            "Preserve Whole Object",
            "Introduce Parameter Object",
        ],
    },
    {
        "id": "data_clumps",
        "name": "Data Clumps",
        "description": "Repeated use of identical groups of variables",
        "treatments": [
            "Extract Class",
            "Introduce Parameter Object",
            "Preserve Whole Object",
        ],
    },
    {
        "id": "switch_statements",
        "name": "Switch Statements",
        "description": "Complex switch operator or sequence of if statements",
        "treatments": [
            "Extract Method & then Move Method",
            "Replace Type Code with Subclasses or Replace Type Code with State/Strategy",
            "Replace Conditional with Polymorphism",
            "Replace Parameter with Explicit Methods",
            "Introduce Null Object",
        ],
    },
    {
        "id": "temporary_field",
        "name": "Temporary Field",
        "description": "Temporary fields get their values only under certain circumstances. Outside of these circumstances, they're empty",
        "treatments": [
            "Extract Class or Replace Method with Method Object.",
            "Introduce Null Object",
        ],
    },
    {
        "id": "refused_bequest",
        "name": "Refused Bequest",
        "description": "If a subclass uses only some of the methods and properties inherited from its parents. The unneeded methods may simply go unused or be redefined and give off exceptions",
        "treatments": ["Replace Inheritance with Delegation", "Extract Superclass"],
    },
    {
        "id": "acdi",
        "name": "Alternative Classes with Different Interfaces",
        "description": "Two classes perform identical functions but have different method names",
        "treatments": [
            "Rename Method",
            "Move Method, Add Parameter & Parameterize Method",
            "Extract Superclass",
        ],
    },
    {
        "id": "divergent_change",
        "name": "Divergent Change",
        "description": "Having to change many unrelated methods when you make changes to a class",
        "treatments": ["Extract Class", "Extract Superclass & Extract Subclass"],
    },
    {
        "id": "shotgun_surgery",
        "name": "Shotgun Surgery",
        "description": "Making any modifications requires that you make many small changes to many different classes",
        "treatments": ["Move Method & Move Field", "Inline Class"],
    },
    {
        "id": "parallel_inheritance_hierarchies",
        "name": "Parallel Inheritance Hierarchies",
        "description": "Creation of a subclass for a class leads to the needing to create a subclass for another class",
        "treatments": ["Move Method & Move Field"],
    },
    {
        "id": "comments",
        "name": "Comments",
        "description": "A method is filled with explanatory comments",
        "treatments": [
            "Extract Variable",
            "Extract Method",
            "Rename Method",
            "Introduce Assertion",
        ],
    },
    {
        "id": "duplicate_code",
        "name": "Duplicate Code",
        "description": "Two code fragments look almost identical",
        "treatments": [
            "Extract Method",
            "Extract Method & Pull Up Field",
            "Pull Up Constructor Body",
            "Form Template Method",
            "Substitute Algorithm",
            "Extract Superclass",
            "Extract Class" "Consolidate Conditional Expression and use Extract Method",
            "Consolidate Duplicate Conditional Fragments",
        ],
    },
    {
        "id": "lazy_class",
        "name": "Lazy Class",
        "description": "If a class doesn't do much, it can be categorized as a Lazy Class",
        "treatments": ["Inline Class", "Collapse Hierarchy"],
    },
    {
        "id": "data_class",
        "name": "Data Class",
        "description": "A data class refers to a class that contains only fields and crude methods for accessing them (getters and setters). These are simply containers for data used by other classes. These classes don't contain any additional functionality and can't independently operate on the data that they own",
        "treatments": [
            "Encapsulate Field",
            "Encapsulate Collection ",
            "Move Method and Extract Method",
            "Remove Setting Method and Hide Method",
        ],
    },
    {
        "id": "dead_code",
        "name": "Dead Code",
        "description": "A variable, parameter, field, method or class is no longer used (usually because it's obsolete)",
        "treatments": [
            "Remove Unused Code",
            "Inline Class or Collapse Hierarchy",
            "Remove Parameter",
        ],
    },
    {
        "id": "spec_gen",
        "name": "Speculative Generality",
        "description": "There's an unused class, method, field or parameter",
        "treatments": [
            "Collapse Hierarchy",
            "Inline Class",
            "Inline Method",
            "Remove Parameter",
        ],
    },
    {
        "id": "feature_envy",
        "name": "Feature Envy",
        "description": "A method accesses the data of another object more than its own data",
        "treatments": [
            "Move Method",
            "Extract Method",
            "Extract Method",
            "Extract Method with Move Method",
        ],
    },
    {
        "id": "in_int",
        "name": "Inappropriate Intimacy",
        "description": "One class uses the internal fields and methods of another class",
        "treatments": [
            "Move Method & Move Field",
            "Extract Class & Hide Delegate",
            "Change Bidirectional Association to Unidirectional",
            " Replace Delegation with Inheritance",
        ],
    },
    {
        "id": "message_chains",
        "name": "Message Chains",
        "description": "In code you see a series of calls resembling $a->b()->c()->d()",
        "treatments": ["Hide Delegate", "Extract Method & Move Method"],
    },
    {
        "id": "middle_man",
        "name": "Middle Man",
        "description": "A class performs only one action that is delegating work to another class and does nothing else",
        "treatments": ["Remove Middle Man"],
    },
    {
        "id": "incomplete_lc",
        "name": "Incomplete Library Class",
        "description": "Having to augment a library to suit the users need repeatedly",
        "treatments": ["Local Extension"],
    },
]